config/routes.rb
Rails.application.routes.draw do
  get 'licitacion/licitacion'
  get 'audiencia/detalle'
  get 'audiencia/detalleaudiencia'
  get 'buscador/activo'
  get 'index/index'

  get 'index/quees'
  get 'index/top_compradores_del_estado'
  get 'index/top_lobbysta_proveedor'
  get 'index/top_organismos_con_mas_audiencias'
  get 'index/top_proveedores_del_estado'




  root to: 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/index/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
    <div class="filtro-negro"></div>
    <div class="carousel-item active banner-1">
      <img class="d-block w-100" src="/static/img/banner-1.png" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
            <h3 id="car" class="texto-banner-1">Esta es la 1ra plataforma de cruce de datos de Lobby y Compras</h3>
            <%= link_to 'Ver más', index_quees_path  %>
        </div>
    </div>
    <div class="carousel-item banner-2">
      <img class="d-block w-100" src="/static/img/banner-2.png" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
            <h3 id="car"class="texto-banner-2">¿Quieres saber si el Lobby impacta las Compras Públicas?</h3>
            <%= link_to 'Revisa acá', controller: 'buscador', action:'activo', :class =>'boton-banner-2' %>
        </div>
          
    </div>
    <div class="carousel-item banner-3">
      <img class="d-block w-100" src="/static/img/banner-3.png" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
            <h3 id="car"class="texto-banner-3">¿Con quienes se reunieron los principales compradores del Estado?</h3>
            <%= link_to 'Busca acá', controller: 'index', action:'top_compradores_del_estado' %>
        </div>
    </div>
      
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="info_box_grande">
            <h2>REVISA LOS TOP 10 COMPRADORES DEL ESTADO CON MAYOR NÚMERO DE <br>
            AUDIENCIAS OTORGADAS A PROVEEDORES</h2>
            <%= link_to 'Ver más', controller: 'index', action:'top_organismos_con_mas_audiencias' %>
            <div class="degradado_grande"></div>
            <img  src="/static/img/01.jpg" alt="First slide">
        </div>
    </div> 
    <div class="col-lg-6">
        <div class="info_box">
            <h2>BUSCA POR COMPRADORES O <br>
            PROVEEDORES</h2>
            <%= link_to 'Ver más', controller: 'buscador', action:'activo' %>
            <div class="degradado_izquierda"></div>
            <img  src="/static/img/02.jpg" alt="First slide">
        </div>
        
        <div class="info_box">
            <h2>TOP 10 LOBBISTAS</h2>
            <%= link_to 'Ver más', controller: 'index', action:'top_lobbysta_proveedor' %>
             
            <p>¿Quieres saber quienes son los proveedores <br>
            con más audiencias de lobby?</p>
            <div class="degradado_izquierda"></div>
            <img  src="/static/img/03.jpg" alt="First slide">
        </div>

        <div class="info_box">
            <h2>CONOCE QUIENES SON LOS MAYORES COMPRADORES DEL ESTADO</h2>
            <%= link_to 'Ver más', controller: 'index', action:'top_compradores_del_estado' %>
            <div class="degradado_izquierda"></div>
            <img  src="/static/img/04.jpg" alt="First slide">
        </div>
    </div>
     <div class="col-lg-6">
        <div class="info_box_right">
            <h2>TOP 10 PROVEEDORES</h2>
            <%= link_to 'Ver más', controller: 'index', action:'top_proveedores_del_estado' %>
            <p>Revisa quienes son los mayores proveedores <br>
             del Estado.</p>
            <div class="degradado_derecha"></div>
            <img  src="/static/img/05.jpg" alt="First slide">
        </div>
    </div>



   

</div>

app/views/index/quees.html.erb
<div class="row">
<section class="container" style="background:#fff;" id="queeslobbyscaliza">
  
    <div class="col-lg-12 contenedor_arriba">
        <div class="col-lg-6 text_arriba">
             <h1>Qué es Lobbyscaliza</h1>
             <p>Lobbyscaliza es una plataforma ideada por Fundación Multitudes dispuesta al servicio de la comunidad, construida sobre datos provistos por organismos públicos del Estado de Chile relativos a Lobby y Compras Públicas. La principal finalidad de esta herramienta es entregar un insumo que promueva la investigación y fiscalización, las que pueden provenir indistintamente de la sociedad civil, academia, organismos fiscalizadores, entre otros.</p>
        </div>
        <div class="col-lg-6 img_arriba">
            <div class="degradado_grande"></div>
             <img  src="/static/img/06.jpg" alt="First slide">
        </div>
    </div>
    <div class="col-lg-12 contenedor_abajo">
          <div class="col-lg-6 img_abajo">
             <div class="degradado_grande"></div>
             <img  src="/static/img/07.jpg" alt="First slide">
        </div>
        <div class="col-lg-6 text_abajo">
            <h1>¿Cuál es su uso?</h1>
            <p>Es una plataforma de uso transversal, que presta sus servicios a todo aquel que tenga la necesidad de observar relaciones entre Lobby y Compras realizadas en el Estado de Chile. Mediante el uso de buscadores podrás encontrar información individualizada sobre las audiencias por Ley de Lobby que han mantenido tanto proveedores como organismos compradores del Estado, que hayan sido transadas mediante el sistema de Mercado Público.</p>
        </div>
        
    </div>
</section>
</div>

app/views/index/top_compradores_del_estado.html.erb
 <section class="container">
    
    <h2>TOP 10 COMPRADORES DEL ESTADO </h2>
    <button id="top10compradoresdelestado_btn" class="boton_json">JSON</button>
    <table class="table" id="top10compradoresdelestado">
    <thead>
        <tr>
        <th scope="col" class="text-center">Rut</th>
        <th scope="col" class="text-center">Nombre comprador</th>
        <th scope="col" class="text-center">Monto</th>
        <th scope="col" class="text-center">Cantidad de contratos </th>
        <th scope="col" class="text-center">Detalle</th>
        </tr>
    </thead>
    <tbody>

    <% @queryy.each do |t| %>
            <tr>
                <td scope="col" class="text-center">
                     <%=  link_to controller: 'buscador', action: 'activo', rutpasivo: t[0], tipo: 'pasivo', desde: '2014-01-01', hasta: '2019-02-02', target: '_blank' do %>
                       <%= t[0] %>
                    <% end %>
                </td><!-- Rut -->
                <td scope="col" class="text-center"><%= t[1] %></td><!-- Nombre de compradores -->
                <td scope="col" class="text-center">$<%= t[2].to_s.gsub(/\d(?=(...)+$)/, '\0.') %></td><!-- Monto adjudicados -->
                <td scope="col" class="text-center"><%= contratos_pasivos(t[0]).first[0] %></td><!-- Cantidad de contratos -->
                <td scope="col" class="text-center">
                    <%=  link_to controller: 'buscador', action: 'activo', rutpasivo: t[0], tipo: 'pasivo', desde: '2014-01-01', hasta: '2019-02-02', target: '_blank' do %>
                        <i class='fas fa-search'></i>
                    <% end %>
                </td>
            </tr>
        <% end %>

    </tbody>
    </table>
</section>
 

app/views/index/top_lobbysta_proveedor.html.erb
<section class="container">
    <h2>TOP 10 LOBBISTA - PROVEEDOR</h2>
    <button id="top_lobbysta_proveedor_btn" class="boton_json">JSON</button>
    <table class="table" id="top_lobbysta_proveedor">
    <thead>
        <tr>
        <th scope="col" class="text-center">Rut</th>
        <th scope="col" class="text-center">Nombre proveedor</th>
        <th scope="col" class="text-center">Cantidad de audiencias</th>
        <th scope="col" class="text-center">Cantidad de contratos adjudicados </th>
        <th scope="col" class="text-center">Monto total </th>
        </tr>
    </thead>
    <tbody>

            <% @top10_lobbysta_proveedor.each do |t| %>
            <tr>
                <td scope="col" class="text-center">
                    <%= link_to controller: 'buscador', action: 'activo', rut: t[0], tipo: 'activo', desde: '2014-01-01', hasta: '2019-02-02', target: '_blank' do %>
                        <%=  t[0] %>
                    <% end %>
                </td> <!-- Rut -->
                <td scope="col" class="text-center"><%= t[1] %></td> <!-- Nombre -->
                <td scope="col" class="text-center"><%= audiencias(t[0]).first[0] %></td> <!-- Cantidad audiencias -->
                <td scope="col" class="text-center"><%= t[2] %></td><!-- Cantidad Contratos -->
                <td scope="col" class="text-center">$<%= t[3].to_s.gsub(/\d(?=(...)+$)/, '\0.')    %> </td>

            </tr>
            <% end %>

    </tbody>
    </table>
</section>

app/views/index/top_proveedores_del_estado.html.erb
 <section class="container">
    <h2>TOP 10 PROVEEDORES DEL ESTADO</h2>
    <button id="top_proveedores_estado_btn" class="boton_json">JSON</button>
    <table class="table" id="top_proveedores_estado">
    <thead>
        <tr>
        <th scope="col" class="text-center">Rut</th>
        <th scope="col" class="text-center">Nombre proveedor</th>
        <th scope="col" class="text-center">Cantidad de contratos adjudicados</th>
        <th scope="col" class="text-center">Monto total </th>
        <th scope="col" class="text-center">Detalle </th>
        </tr>
    </thead>
    <tbody>
        <% @topproveedoresdelestado.each do |t| %>
            <tr>
                  <td scope="col" class="text-center">
                    <%= link_to controller: 'buscador', action: 'activo', rut: t[0], tipo: 'activo', desde: '2014-01-01', hasta: '2019-02-02', target: '_blank' do %>
                        <%=  t[0] %>
                    <% end %>
                </td> <!-- Rut -->
                <td scope="col" class="text-center"><%= t[1] %></td>
                <td scope="col" class="text-center"><%= cantidad_de_contratos_adjuntos(t[0]).first[0] %></td> <!-- Cantidad de adjudicaciones -->
                <td scope="col" class="text-center">$<%= t[2].to_s.gsub(/\d(?=(...)+$)/, '\0.') %></td> <!-- Monto total -->
                <td scope="col" class="text-center">
                    <%= link_to controller: 'buscador', action: 'activo', rut: t[0], tipo: 'activo', desde: '2014-01-01', hasta: '2019-02-02', target: '_blank' do %>
                        <i class='fas fa-search'></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
    </table>
</section> 